### ISSUE TITLE
Unable to build on macOS 10.14.2

### ISSUE THREAD

**Issue by kexoyi** [debauchee/barrier#235]
Server: Windows 10 Pro 1709

Client: macOS Mojave 10.14.2

Version: 2.2

I am unable to build Barrier on macOS. I was able to build it just fine Windows. When the program is created, finder puts a prohibited sign on the icon telling me that the program is incomplete or damaged. I also inspected the package's contents and there is nothing in there accept the app icon.

Here is a Pastebin of what happens when I run the script:
https://pastebin.com/V2iAwWge

I have noticed that there is a fatal error saying "fatal: not a git repository (or any of the parent directories): .git". I am thinking this is the cause but have no clue on how to fix it.

What I do to produce this is simply dropping the script in the terminal and running it.

* When did the problem start to occur? When I ran the script.
* Is there a way to work around it? Unknown 
* Does this bug prevent you from using Barrier entirely? Yes

**Comment by AdrianKoshka** [comment]
Any reason for building barrier yourself instead of using the `.dmg` we provide for 2.11?

**Comment by jwestfall69** [comment]
I ran into that too when making debug builds on osx, Try this

Go into build/bundle/ and edit build_installer.sh.  This script is responsible for populating Barrier.app with everything it needs and generating the .dmg file.

Near the top remove or comment out the following

```
# sanity check so we don't distribute packages full of debug symbols
if [ "Debug" != "Release" ]; then
    echo Will only build installers for Release builds
    exit 1
fi
```

I also stop it from making the dmg as the debug build are too big for it causing the process to error out and leave the temp dmg image mounted.  You can stop it by putting an ```exit``` right before the following block in the script (near the bottom).

```
# create the DMG to be distributed in build/bundle
cd ../../..
hdiutil create -size 64m -fs HFS+ -volname "Barrier" temp.dmg || exit 1
hdiutil attach temp.dmg -mountpoint mnt || exit 1
```

Then run the script.

**Comment by kexoyi** [comment]
You saved the day @jwestfall69 I have both Windows and macOS on 2.2! Oddly enough now on both ends it is saying "Barrier is starting." again. But I am getting different errors than I had before I build 2.2.

Error on Windows:
> INFO: connecting to service...
> ERROR: ipc connection error, code=19
> ERROR: ipc connection error, connection refused

Error on macOS:
> WARNING: failed to connect to server: Timed out
    /Users/user/Downloads/barrier-master/src/lib/barrier/ClientApp.cpp,303
> NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
    /Users/user/Downloads/barrier-master/src/lib/client/Client.cpp,143
> INFO: OpenSSL 1.0.2q  20 Nov 2018
    /Users/user/Downloads/barrier-master/src/lib/net/SecureSocket.cpp,851

I double checked my Windows firewall just to be safe and I have allowed barrier, barriers, and barrierc as well.

**Comment by jwestfall69** [comment]
The IPC issue on windows is because the barrierd service isnt running.  Its normally installed/started by the barrier installer.  See if its under the list of services and start it.  If its not there, you likely need to manually added it.  To do that check the ```[Run]``` section in dist/inno/barrier.iss.in for details about what the installer is doing to install/start it.

**Comment by kexoyi** [comment]
So I decided to go back to 2.1.1 on windows and Mac. Here are my logs now.

Mac:

> [2019-01-21T20:56:01] INFO: starting client
> [2019-01-21T20:56:01] INFO: config file: /var/folders/nz/w4stf_9d5s5fkg5bv4s0xcbw0000gn/T/Barrier.tkPZuN
> [2019-01-21T20:56:01] INFO: log level: INFO
> 2019-01-21 20:56:01.302 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699174] starting cocoa loop
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> 2019-01-21 20:56:01.311 barrierc[32640:1699190] pid(32640)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
> [2019-01-21T20:56:01] INFO: drag and drop enabled
> [2019-01-21T20:56:01] NOTE: started client
> [2019-01-21T20:56:01] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
> [2019-01-21T20:56:01] INFO: OpenSSL 1.0.2n  7 Dec 2017
> [2019-01-21T20:56:16] WARNING: failed to connect to server: Timed out
> [2019-01-21T20:56:17] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
> [2019-01-21T20:56:17] INFO: OpenSSL 1.0.2n  7 Dec 2017
> [2019-01-21T20:56:32] WARNING: failed to connect to server: Timed out
> [2019-01-21T20:56:33] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
> [2019-01-21T20:56:33] INFO: OpenSSL 1.0.2n  7 Dec 2017

Windows:

> [2019-01-21T20:53:49] INFO: connecting to service...
> [2019-01-21T20:53:49] INFO: connection established
> [2019-01-21T20:53:48] INFO: using last known command: "C:/Program Files/Barrier/barrierc.exe" -f --no-tray --debug INFO --name DESKTOP-4S2N8J3 --ipc --stop-on-desk-switch --enable-drag-drop --enable-crypto --profile-dir "C:\Users\user\AppData\Local\Barrier" [192.168.7.40]:24800
> [2019-01-21T20:53:48] INFO: service command updated
> [2019-01-21T20:53:48] INFO: starting new process as privileged user
> [2019-01-21T20:53:48] INFO: server status: active
> [2019-01-21T20:53:48] INFO: drag and drop enabled
> [2019-01-21T20:53:48] ERROR: failed to get desktop path, no drop target available, error=2
> [2019-01-21T20:53:48] NOTE: started client
> [2019-01-21T20:53:48] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
> [2019-01-21T20:53:48] INFO: OpenSSL 1.0.2l 25 May 2017
> [2019-01-21T20:53:49] WARNING: failed to connect to server: Connection was refused
> [2019-01-21T20:53:49] INFO: server status: active
> [2019-01-21T20:53:50] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800
> [2019-01-21T20:53:50] INFO: OpenSSL 1.0.2l 25 May 2017
> [2019-01-21T20:53:51] WARNING: failed to connect to server: Connection was refused
> [2019-01-21T20:53:52] NOTE: connecting to '192.168.7.40': 192.168.7.40:24800

**Comment by AdrianKoshka** [comment]
Perhaps windows was just being wonky about starting a service?

**Comment by mirh** [comment]
Could it have something to do with ports being busy or something?

Error 19 [should be](https://doc.qt.io/qt-5/qabstractsocket.html#SocketError-enum) OperationError, and I just noticed how oddly 24801 is reported in use even though config has 24800. 
And as mentioned in https://github.com/symless/synergy-core/issues/6458, after killing and restarting everything it seemed to be solved.

**Comment by ExpandingMan** [comment]
When using windows as client and linux as server, I get (on windows)
```
[2020-10-29T19:13:44] ERROR: ipc connection error, connection refused
[2020-10-29T19:13:45] INFO: connecting to service...
```
Were you implying the service may not be running on linux, or on windows?  On linux, I have the server running as `barriers -f -c barrier.conf` with a simple screen config.  On windows I have no idea what's happening because it's windows.

**Comment by wienyang** [comment]
i reinstalled barrier and it worked fine now

**Comment by cougarten** [comment]
> When using windows as client and linux as server, I get (on windows)
> 
> ```
> [2020-10-29T19:13:44] ERROR: ipc connection error, connection refused
> [2020-10-29T19:13:45] INFO: connecting to service...
> ```
> 
> Were you implying the service may not be running on linux, or on windows? On linux, I have the server running as `barriers -f -c barrier.conf` with a simple screen config. On windows I have no idea what's happening because it's windows.
> 
> Update: I was also having the windows config file issue which mysteriously seems to have solved itself. However, no matter what I do I seem to get the ipc connection error only on windows. The linux machines all seem to be able to connect to each other.

I had this error on windows, even before clicking "start". The problem was the service not running on the windows machine. You can check in the task manager, it has a services tab. From there you can also get to the system settings for services and see if it's disabled and if it's set to launch with windows or not.

**Comment by Hocnonsense** [comment]
I got this error after kill `barrier` in Windows Task Manager.

**Comment by matjaz321** [comment]
> 
> 
> I got this error after kill `barrier` in Windows Task Manager.
> version: 2.3.3-release-3395cca9

Same

**Comment by Hocnonsense** [comment]
> > I got this error after kill `barrier` in Windows Task Manager.
> > version: 2.3.3-release-3395cca9
> 
> Same, but I fixed it by re-installing

I restart the computer and `barrier` run again. It seems that the server of `barrier` start automatically and only once?

**Comment by mirh** [comment]
Check the barrier service.

**Comment by AymenFJA** [comment]
I fixed it by going to the `Task Manager` and switch to the `service` tab, look for `barrier` and right-click on it, and `start` as it was stopped for some reason.

**Comment by VNRARA** [comment]
Years later and I still don't get why there isn't some sort of auto restart of this programmed into barrier to auto restart.

**Comment by ingxfm** [comment]
As for @jwestfall69 and @AymenFJA, the Barrier service was not running, in my case.

**Comment by jhgorse** [comment]
Where is the code for registering the service on windows installation?

**Comment by sumless** [comment]
This issue happened to me while upgrading from Barrier 2.3.3 to Barrier 2.3.4 in a Windows 10 environment.
The following steps resolved my issue:

1. Uninstall Barrier
2. Uninstall Bonjour
3. Reboot the operating system
4. reinstall Barrier

**Comment by JuninhoFreitas** [comment]
Okay,
So here is the solution i found to Windows:
1. Close your barrier (quit option in Task Bar icon)
2. Win+R: services
3. Look for the service of Barrier (you can just start typing barrier and it will find)
4. Start if it is stopped, restart if it is running
5. After started, open barrier as administrator
6. If everything worked, than you will see "Barrier is Running"
7. If not, try to start manully
8. If it still not working, find you ip (the bold Ip in "IP ADRESSES:")
9. Click in the menu bar "Barrier"
10. Select Change Settings
11. In networking, replace the IP in "Address" field with the one you copy
12. Disable SSL and require certificate
13. Click ok, and repeat the process from the step 1
14. Let me know if it worked to you

PT-BR:

Okay,
Então aqui está a solução que encontrei para o Windows:

1. Feche o Barrier (opção de Sair no ícone da barra de tarefas)
2. Win+R: "services"
3. Procure pelo serviço do Barrier (você pode começar a digitar "barrier" e ele encontrará)
4. Inicie se estiver parado, reinicie se estiver em execução
5. Depois de iniciado, abra o Barrier como administrador
6. Se tudo funcionou, você verá "Barrier is Running"
7. Se não, tente iniciar manualmente
8. Se ainda não estiver funcionando, encontre seu IP (o IP em negrito em "IP ADRESSES:")
9. Clique na barra de menu "Barrier"
10. Selecione Alterar Configurações
11. Na rede, substitua o IP no campo "Endereço" pelo que você copiou
12. Desative SSL e exigir certificado
13. Clique em OK e repita o processo a partir do passo 1
14. Me avise se funcionou para você.

**Comment by Rivonivo** [comment]
> Okay, So here is the solution i found to Windows:
> 
> 1. Close your barrier (quit option in Task Bar icon)
> 2. Win+R: services
> 3. Look for the service of Barrier (you can just start typing barrier and it will find)
> 4. Start if it is stopped, restart if it is running
> 5. After started, open barrier as administrator
> 6. If everything worked, than you will see "Barrier is Running"
> 7. If not, try to start manully
> 8. If it still not working, find you ip (the bold Ip in "IP ADRESSES:")
> 9. Click in the menu bar "Barrier"
> 10. Select Change Settings
> 11. In networking, replace the IP in "Address" field with the one you copy
> 12. Disable SSL and require certificate
> 13. Click ok, and repeat the process from the step 1
> 14. Let me know if it worked to you
> 
> PT-BR:
> 
> Okay, Então aqui está a solução que encontrei para o Windows:
> 
> 1. Feche o Barrier (opção de Sair no ícone da barra de tarefas)
> 2. Win+R: "services"
> 3. Procure pelo serviço do Barrier (você pode começar a digitar "barrier" e ele encontrará)
> 4. Inicie se estiver parado, reinicie se estiver em execução
> 5. Depois de iniciado, abra o Barrier como administrador
> 6. Se tudo funcionou, você verá "Barrier is Running"
> 7. Se não, tente iniciar manualmente
> 8. Se ainda não estiver funcionando, encontre seu IP (o IP em negrito em "IP ADRESSES:")
> 9. Clique na barra de menu "Barrier"
> 10. Selecione Alterar Configurações
> 11. Na rede, substitua o IP no campo "Endereço" pelo que você copiou
> 12. Desative SSL e exigir certificado
> 13. Clique em OK e repita o processo a partir do passo 1
> 14. Me avise se funcionou para você.

i love u <3 searches for 2 hours now your way worked
