### ISSUE TITLE
macOS scrolling on client

### ISSUE THREAD

**Issue by sheykh-sleky** [debauchee/barrier#502]
### Operating Systems ###

Server: macOS 10.15.1

Client: macOS 10.14.6

### Barrier Version ###

v2.3.2-Release-210c2b70

### Steps to reproduce bug ###

1.  Connections seem fine, able to connect client to server
2.  Mouse movement across screen fine
3.  Mouse click and right click (2 finger click) work fine
4.  3-finger drag works fine
5.  Scrolling up/down/left/right doesn't work on client

### Other info ###

* When did the problem start to occur? Always
* Is there a way to work around it? No - arrow keys to move the info on screen
* Does this bug prevent you from using Barrier entirely? Yes/No - the mouse moves, but no scrolling....

See attached Debug2 logfile.

TIA
[Debug2.log](https://github.com/debauchee/barrier/files/3870455/Debug2.log)

**Comment by oristopo** [comment]
Scrolling also fails on Windows 10 client from macOS server.
I guess that this is not a new problem;
I seem to recall the same on Synergy nearly 10 years ago.
Server works better on Windows; can scroll on macOS client from it.

**Comment by sheykh-sleky** [comment]
Literally don't have a physical Windows box...

That's interesting, does anyone have a *nix box they could setup as a server and see if scrolling works on a different OS client?  (Again, hardware limitation on OS's.  LOL)

My guess is that if the issue is having a macOS as the server, something to at least isolate a lil further I would imagine...  Sadly whenever I review any of the logs, there aren't any "errors" that I can see.  <shrug>

**Comment by waitaria** [comment]
Scrolling works fine from a Ubuntu 18.04 server, and a macOS 10.15.2 client. When I reverse the roles, scrolling on the (ubuntu) client does not work.

**Comment by hugoisaac** [comment]
I have the same issue. Mouse scroll wheel doesn't work when using macOS server and Linux client. I thought it was probably related to my mouse (Logitech MX Master 3), but it may be a general problem from what I'm seeing here.

- Barrier Version: 2.3.3-release-3395cca9
- Server: macOS Catalina 10.15.6
- Client: elementary OS 5.1.7 Hera (built on Ubuntu 18.04.4 LTS)

**Comment by RazaGR** [comment]
> I have the same issue. Mouse scroll wheel doesn't work when using macOS server and Linux client. I thought it was probably related to my mouse (Logitech MX Master 3), but it may be a general problem from what I'm seeing here.
> 
> * Barrier Version: 2.3.3-release-3395cca9
> * Server: macOS Catalina 10.15.6
> * Client: elementary OS 5.1.7 Hera (built on Ubuntu 18.04.4 LTS)

You found any solution? I have same macOS server /Ubuntu  client setup with same issue.

**Comment by RazaGR** [comment]
my issue is solved by decreasing mouse speed on server

**Comment by drew-t** [comment]
> my issue is solved by decreasing mouse speed on server

appears to be related to scroll speed setting. even raising it after I lowered it appears to still work fine.

**Comment by hugoisaac** [comment]
> my issue is solved by decreasing mouse speed on server

Thanks! This also fixed it for me. I've still not decided which works better for me, if using Linux or macOS as the server. This give some points to macOS as the server.

**Comment by Nezteb** [comment]
For what it's worth: I had this same issue with a Windows server and Mac client. I have a Logitech MX Ergo bluetooth mouse, and the Logitech Options software has a thing called "Smooth scrolling". Turning that off makes scrolling work on all clients. 👍

**Comment by JPHFan** [comment]
I actually experience this in a slightly different way. Windows server, mac client, no special software. Scrollwheel generally does work, but occasionally stops working on the mac client. The fix I have used is to reload on the mac client, sometimes a few times, until the scrollwheel continues working.

Not sure if this is a totally different issue or just a subtle nuance to the same issue.

**Comment by bjohas** [comment]
Same issue here (Ubuntu laptop as server, Mac client) - reducing the scrolling speed on the mac (via the usual system preferences) enabled two-finger scrolling on the Mac.

**Comment by rstacruz** [comment]
I'm using a MacOS server, and a Linux client here, along with Logitech's "Logi Options" app. Setting the scroll speed to the minimum in the System Preferences made scrolling work on the client for me.

![image](https://user-images.githubusercontent.com/74385/120415582-2604d780-c39f-11eb-96c0-6b006f5b9ef0.png)

**Comment by Pablokiryu** [comment]
I have the same Mouse as @Nezteb , Windows 10 server, Old imac Running Pop_OS client. 
His solution (disabling smooth scroll on Logitech options on server) seems to have fixed the issue for me as well.

**Comment by dinomite** [comment]
Oh wow, I have the same setup as @rstacruz, a macOS server using a Logitech mouse and the Logi Options app for configuring that mouse.

For years I've not been able to scroll on my macOS client machine while using Synergy, but decided I'd revisit the problem now that I'm using Barrier. Turning the scrolling speed down to the minimum in System Preferences fixed it and did not affect the scroll speed on the server (i.e. the setting in Logi Options is still respected). Kudos @rstacruz!

**Comment by matiasbaldanza** [comment]
> For what it's worth: I had this same issue with a Windows server and Mac client. I have a Logitech MX Ergo bluetooth mouse, and the Logitech Options software has a thing called "Smooth scrolling". Turning that off makes scrolling work on all clients. 👍

Same problem here: I have a Windows Server with a Logitech MX Vertical and a Mac client. Everything worked fine with the mouse except scrolling in the Mac. I disabled smooth scrolling in Logitech Options on the server and mouse scroll started working on the Mac client. Thank you!

**Comment by chomookun** [comment]
> I'm using a MacOS server and a Linux client here along with Logitech's "Logi Options" app. Setting the scroll speed to the minimum in the System Preferences made scrolling work on the client for me.
> 
> ![image](https://user-images.githubusercontent.com/74385/120415582-2604d780-c39f-11eb-96c0-6b006f5b9ef0.png)

it works. thanks.!!!!

**Comment by e-rocky** [comment]
> > my issue is solved by decreasing mouse speed on server
> 
> appears to be related to scroll speed setting. even raising it after I lowered it appears to still work fine.

Worked for me, thanks ! 🥳
